language: node_js
node_js:
- 6.11.3
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - sudo pip install -r requirements.txt
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
script:
  - pybot test.robot
notifications:
  email:
    - stollenwerk@kitconcept.com
